In [1]:
import pandas as pd

1. Создавйте DataFrames, прочитав файлы https://cloud.ocherepanov.ru/s/gpS7HmfGLpqSSaa и https://cloud.ocherepanov.ru/s/ddgJPBNR2zDJbFL

In [15]:
customers_df = pd.read_csv('customers.csv')
customers_df.head()

         id             name    segment           state             city
0  CG-12520      Claire Gute   Consumer        Kentucky        Henderson
1  DV-13045  Darrin Van Huff  Corporate      California      Los Angeles
2  SO-20335   Sean O'Donnell   Consumer         Florida  Fort Lauderdale
3  BH-11710  Brosina Hoffman   Consumer      California      Los Angeles
4  AA-10480     Andrew Allen   Consumer  North Carolina          Concord

In [35]:
orders_df = pd.read_csv('orders.csv', decimal=',')
orders_df.head()

       id  order_date ship_mode customer_id    sales
0  100006  2014-09-07  Standard    DK-13375  377.970
1  100090  2014-07-08  Standard    EB-13705  699.192
2  100293  2014-03-14  Standard    NF-18475   91.056
3  100328  2014-01-28  Standard    JC-15340    3.928
4  100363  2014-04-08  Standard    JM-15655   21.376

2. Выведите все заказы клиенты с именем Andrew Allen.

In [36]:
customer_id = customers_df[customers_df['name'] == 'Andrew Allen'].iloc[0]['id']
customer_orders = orders_df[orders_df['customer_id'] == customer_id]
customer_orders

          id  order_date ship_mode customer_id     sales
651   155271  2014-05-04  Same Day    AA-10480    27.460
1930  114601  2016-08-26  Standard    AA-10480  1157.980
2035  121671  2016-07-17  Standard    AA-10480   589.520
3084  114412  2017-04-15  Standard    AA-10480    15.552

3. Соедините таблицы в одну и сохраните в отдельном файле.

In [37]:
merged_customers_orders_df = pd.merge(
    orders_df, customers_df, left_on='customer_id', right_on='id')
merged_customers_orders_df.to_csv('merged_customers_orders.csv', index=False)
merged_customers_orders_df.head()

,id_x,order_date,ship_mode,customer_id,sales,id_y,name,segment,state,city
0,100006,2014-09-07,Standard,DK-13375,377.970,DK-13375,Dennis Kane,Consumer,Ohio,Marion
1,100090,2014-07-08,Standard,EB-13705,699.192,EB-13705,Ed Braxton,Corporate,Ohio,Akron
2,100293,2014-03-14,Standard,NF-18475,91.056,NF-18475,Neil Franzosisch,Home Office,Illinois,Rockford
3,100328,2014-01-28,Standard,JC-15340,3.928,JC-15340,Jasper Cacioppo,Consumer,California,Los Angeles
4,100363,2014-04-08,Standard,JM-15655,21.376,JM-15655,Jim Mitchum,Corporate,New Jersey,Bridgeton

4. Посчитайте количество заказов клиентов из Los Angeles.

In [38]:
len(merged_customers_orders_df[merged_customers_orders_df['city'] == 'Los Angeles'])

357

5. Сгруппируйте заказы по городам и посчитайте их количестово и сумму.

In [39]:
city_stats = merged_customers_orders_df.groupby('city').agg(
    order_count=('sales', 'size'),
    total_sales=('sales', 'sum')
)
city_stats.head()

              order_count  total_sales
city
Akron                  19     5193.680
Albuquerque             7     2327.244
Allen                   4      649.376
Amarillo                7     3690.284
Apple Valley            3      908.821

6. Выведите топ-5 людей, котороые больше всего потратили денег.

In [42]:
top_5_customers = merged_customers_orders_df.groupby('customer_id')[
    'sales'].sum().nlargest(5)
top_5_customers

customer_id
SM-20320    25043.050
TC-20980    19052.218
RB-19360    15117.339
TA-21385    14595.620
AB-10105    14473.571
Name: sales, dtype: float64

7. Посчитайте средний чек по всем штатам за каждый год.

In [45]:
merged_customers_orders_df['order_date'] = pd.to_datetime(
    merged_customers_orders_df['order_date'])
merged_customers_orders_df['year'] = merged_customers_orders_df['order_date'].dt.year
merged_customers_orders_df.head()

,id_x,order_date,ship_mode,customer_id,sales,id_y,name,segment,state,city,year
0,100006,2014-09-07,Standard,DK-13375,377.970,DK-13375,Dennis Kane,Consumer,Ohio,Marion,2014
1,100090,2014-07-08,Standard,EB-13705,699.192,EB-13705,Ed Braxton,Corporate,Ohio,Akron,2014
2,100293,2014-03-14,Standard,NF-18475,91.056,NF-18475,Neil Franzosisch,Home Office,Illinois,Rockford,2014
3,100328,2014-01-28,Standard,JC-15340,3.928,JC-15340,Jasper Cacioppo,Consumer,California,Los Angeles,2014
4,100363,2014-04-08,Standard,JM-15655,21.376,JM-15655,Jim Mitchum,Corporate,New Jersey,Bridgeton,2014

In [69]:
avg_sales = merged_customers_orders_df.groupby(['state', 'year'])['sales'].mean().reset_index()
avg_sales.rename(columns={'sales': 'avg_sales'}, inplace=True)
avg_sales.head()

     state  year   avg_sales
0  Alabama  2014  425.521556
1  Alabama  2015  501.367650
2  Alabama  2016  854.347188
3  Alabama  2017  417.962833
4  Arizona  2014  475.161875

8. Создайте Dataframe, прочитав файл https://cloud.ocherepanov.ru/s/LArppdaMqACpnpr

In [100]:
winds_df = pd.read_csv('winds.csv')
winds_df = winds_df.sort_values('dt').reset_index(drop=True)
winds_df['group'] = (winds_df['direction'] == 'x').cumsum()
winds_df['dt'] = winds_df.groupby('group')['dt'].transform('min')
winds_df.head()

                    dt direction  value  group
0  2013-09-03 00:00:21         x  -38.0      1
1  2013-09-03 00:00:21         y -297.0      1
2  2013-09-03 00:00:21         z   11.0      1
3  2013-09-03 00:00:23         x  -39.0      2
4  2013-09-03 00:00:23         y -214.0      2

9. С помощью методов unstack и pivot создайте wide-представление, в таком виде: время - высота - скорость по x - скорость по y - скорость по z.

In [96]:
winds_df = winds_df.set_index(['dt', 'direction'])
winds_df.head()

                               value  group
dt                  direction
2013-09-03 00:00:21 x          -38.0      1
                    y         -297.0      1
                    z           11.0      1
2013-09-03 00:00:23 x          -39.0      2
                    y         -214.0      2

In [101]:
wide_pivot_winds_df = winds_df.pivot_table(
    index='dt', columns='direction', values='value')
wide_pivot_winds_df.columns.name = None
wide_pivot_winds_df.rename(
    columns={'x': 'speed_x', 'y': 'speed_y', 'z': 'speed_z'}, inplace=True)
wide_pivot_winds_df.head()

                     speed_x  speed_y  speed_z
dt
2013-09-03 00:00:21    -38.0   -297.0     11.0
2013-09-03 00:00:23    -39.0   -214.0    -28.0
2013-09-03 00:00:27    -28.0   -251.0     44.0
2013-09-03 00:00:31    -33.0   -209.0     87.0
2013-09-03 00:00:35    -30.0   -252.0    -24.0