In [6]:
import pandas as pd
import numpy as np

### Series

1.   Создайте объект Series из питоновского списка, строки и словаря.

In [2]:
pd.Series(['255', '256', '128'])

0    255
1    256
2    128
dtype: object

In [10]:
pd.Series(list('25565'), index=[0, 2, 4, 6, 8])

0    2
2    5
4    5
6    6
8    5
dtype: object

In [5]:
pd.Series({'key1': 'value1', 'key2': 'value2'})

key1    value1
key2    value2
dtype: object

2.   Создайте два объекта Series. Найдите их пересечение и объедиение.

In [84]:
a = pd.Series(np.arange(1, 100, 3))
b = pd.Series(np.arange(2, 50, 2))
#TODO:
print('Intersection:\n', a[a.isin(b)])
print('Union\n', pd.concat([a, b]).unique())

Intersection:
 1      4
3     10
5     16
7     22
9     28
11    34
13    40
15    46
dtype: int32
Union
 [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97  2  6  8 12 14 18 20 24 26 30 32 36 38 42 44
 48]

3.   Создайте объект Series случайных значений. Найдите частоту встречаемоти его элементов.

In [16]:
s = pd.Series(np.random.randint(1, 5, size=10))
print("Series:\n", s)
print("Частота:\n", s.value_counts())

Series:
 0    1
1    2
2    4
3    1
4    4
5    4
6    1
7    2
8    4
9    2
dtype: int32
Частота:
 4    4
1    3
2    3
Name: count, dtype: int64

4.   Создайте объект Series случайных значений. Найдите элементы, индыксы которых кратны 3.

In [18]:
s = pd.Series(np.random.randint(1, 5, size=10))
print("Series:\n", s)
print("Элементы с индексами, кратными 3:\n", s[s.index % 3 == 0])

Series:
 0    2
1    1
2    4
3    2
4    2
5    4
6    3
7    1
8    3
9    4
dtype: int32
Элементы с индексами, кратными 3:
 0    2
3    2
6    3
9    4
dtype: int32

5. Создайте два объекта Series. Получить индексы объекта Series A, данные которых содержатся в объекте Series B.

In [22]:
a = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
b = pd.Series([3, 4, 5, 6, 7])
a[a.isin(b)].index

Index(['c', 'd', 'e'], dtype='object')

6. Преобразовать каждый символ объекта Series в верхний регистр.

In [24]:
s = pd.Series(['apple', 'banana', 'Cherry'])
s.str.upper()

0     APPLE
1    BANANA
2    CHERRY
dtype: object

7. Создайте объект Series строк. Отберите элементы, которые содержат не менее двух гласных.

In [98]:
s = pd.Series(['apple', 'orongo', 'sky', 'beautiful', 'butterfly'])

vowels = 'aeiouAEIOU'
vowel_count = s.apply(lambda x: str(set(x))).str.count(f'[{vowels}]')
s[vowel_count >= 2]

0        apple
3    beautiful
4    butterfly
dtype: object

8. Создайте случайный Series. Найти индексы локальных минимумов.

In [28]:
s = pd.Series(np.random.randn(10))
print("Series:\n", s)

local_min = (s < s.shift(1)) & (s < s.shift(-1))
min_indices = s[local_min].index
print("Индексы локальных минимумов:\n", min_indices.tolist())

Series:
 0    1.917664
1   -1.062247
2   -0.135321
3   -0.864351
4   -0.857566
5   -1.167734
6    0.331369
7    0.922241
8   -1.225970
9    0.726811
dtype: float64
Индексы локальных минимумов:
 [1, 3, 5, 8]

9. Создайте случайный Series. Найдите автокорреляцию.

In [108]:
'''
0: 3 1 4 1 3 2 3 2 4 2
1: n 3 1 4 1 3 2 3 2 4
2: n n 3 1 4 1 3 2 3 2
3: n n n 3 1 4 1 3 2 3
4: n n n n 3 1 4 1 3 2
5: n n n n n 3 1 4 1 3
6: n n n n n n 3 1 4 1
7: n n n n n n n 3 1 4
8: n n n n n n n n 3 1
'''
s = pd.Series(np.random.randint(1, 15, size=100))
print(s)
lags = range(1, 26)
autocorrs = {lag: s.corr(s.shift(lag)) for lag in lags}

print("Автокорреляции:")
for lag, acf in autocorrs.items():
    print(f"   Лаг {lag:2d}: {acf:8.6f}")

0      4
1      7
2      2
3      9
4      5
      ..
95     4
96     8
97     1
98     4
99    11
Length: 100, dtype: int32
Автокорреляции:
   Лаг  1: -0.141935
   Лаг  2: 0.098679
   Лаг  3: -0.209941
   Лаг  4: 0.160888
   Лаг  5: 0.007104
   Лаг  6: 0.002923
   Лаг  7: -0.001170
   Лаг  8: 0.006788
   Лаг  9: 0.022603
   Лаг 10: 0.200033
   Лаг 11: 0.028850
   Лаг 12: -0.141769
   Лаг 13: -0.043544
   Лаг 14: 0.019063
   Лаг 15: 0.369183
   Лаг 16: -0.160695
   Лаг 17: 0.248724
   Лаг 18: -0.218205
   Лаг 19: 0.148848
   Лаг 20: -0.136275
   Лаг 21: 0.107072
   Лаг 22: -0.131781
   Лаг 23: -0.013751
   Лаг 24: 0.002558
   Лаг 25: 0.238700

### DataFrame

1.   Создайте объект DataFrame по загруженному файлу.

In [33]:
df = pd.read_csv('car_prices_jordan.csv', index_col=0)
df.head()

                    Model   Property    Power   Price
0             Byd F0 2018     Manual  1000 CC   6,900
1        Suzuki Alto 2023     manual   800 CC   8,250
2     Suzuki Celerio 2019  Automatic  1000 CC  10,499
3     Changan E Star 2023  Automatic     0 CC  10,990
4  Hyundai Grand i10 2020  Automatic  1250 CC  11,500

2.   Проверьте имеются ли пропущенные данные.

In [34]:
df.isnull().sum()

Model       0
Property    0
Power       0
Price       0
dtype: int64

3.   Переименуйте столбцы так, чтобы они имели русские названия.

In [40]:
df.columns = ['Модель', 'КПП', 'Мощность', 'Цена']
df.head()

                   Модель        КПП Мощность    Цена
0             Byd F0 2018     Manual  1000 CC   6,900
1        Suzuki Alto 2023     manual   800 CC   8,250
2     Suzuki Celerio 2019  Automatic  1000 CC  10,499
3     Changan E Star 2023  Automatic     0 CC  10,990
4  Hyundai Grand i10 2020  Automatic  1250 CC  11,500

4.   Выведете только столбец с названием моделей автомобиля.

In [37]:
df['Модель'].head()

0               Byd F0 2018
1          Suzuki Alto 2023
2       Suzuki Celerio 2019
3       Changan E Star 2023
4    Hyundai Grand i10 2020
Name: Модель, dtype: object

5.   Получите информацию только о автомобилях марки Nissan.

In [53]:
df['Марка'] = df['Модель'].str.split().str[0]
df[df['Марка'] == 'Nissan']

,Модель,КПП,Мощность,Цена,Марка
6,Nissan Micra 2020,Automatic,1500 CC,"11,950",Nissan
50,Nissan Sunny 2022 Facelift,Automatic / S,1600 CC,"19,900",Nissan
56,Nissan Kicks 2022,Automatic / S,1600 CC,"20,900",Nissan
62,Nissan Sunny 2022 Facelift,Automatic / SL,1600 CC,"21,900",Nissan
70,Nissan Kicks 2022,Automatic / SV,1600 CC,"22,900",Nissan
82,Nissan LEAF 2020,Automatic / 40kWh,0 CC,"23,500",Nissan
92,Nissan Navara 2022,manual / CSF 4WD 6MT,2500 CC,"25,000",Nissan
98,Nissan Kicks 2022,Automatic / SL,1600 CC,"25,900",Nissan
103,Nissan Kicks 2022,Automatic / SL,1600 CC,"25,900",Nissan
165,Nissan Xterra 2022,Automatic / SE 2WD,2500 CC,"34,900",Nissan
167,Nissan XTrail 2023,Automatic / S,2500 CC,"34,900",Nissan
187,Nissan Xterra 2022,Automatic / Titanium 2WD,2500 CC,"39,900",Nissan
190,Nissan Pathfinder 2020,Automatic / S 4wd,2500 CC,"40,950",Nissan
296,Nissan Patrol 2023,Automatic,4000 CC,"78,000",Nissan

6.   Получите информацию только о автомобилях не старше 2 лет.

In [62]:
df['Год'] = df['Модель'].str.extract(r'(\d{4})').astype(int)
df[df['Год'] >= 2023]

,Модель,КПП,Мощность,Цена,Марка,Год
1,Suzuki Alto 2023,manual,800 CC,"8,250",Suzuki,2023
3,Changan E Star 2023,Automatic,0 CC,"10,990",Changan,2023
5,Baic X35 2023,manual / MT,1500 CC,"11,900",Baic,2023
12,Changan V3 2023,Automatic,1500 CC\nTurbo,"14,000",Changan,2023
13,Kia Picanto 2023,Automatic,1200 CC,"14,100",Kia,2023
...,...,...,...,...,...,...
354,Porsche 911 2023,manual / Turbo S Cabriolet,3800 CC\nTurbo,"163,000",Porsche,2023
355,Cadillac Escalade 2023,Automatic,6200 CC,"165,800",Cadillac,2023
358,Land Rover Range Rover 2023,Automatic / SE,3000 CC,"187,350",Land,2023
361,Land Rover Range Rover 2023,Automatic / HSE,3000 CC,"203,350",Land,2023
365,Cadillac Ecalade V 2023,manual,6200 CC,"250,000",Cadillac,2023

7.   Добавьте столбец с ценой автомобилей в рублях.

In [68]:
df = df.rename(columns={'Цена': 'Цена, дол.'})
df['Цена, дол.'] = df['Цена, дол.'].astype(str).str.replace(',', '').astype(float)
df['Цена, руб.'] = df['Цена, дол.'] * 83.35
df

,Модель,КПП,Мощность,"Цена, дол.",Марка,Год,"Цена, руб."
0,Byd F0 2018,Manual,1000 CC,6900.0,Byd,2018,575115.00
1,Suzuki Alto 2023,manual,800 CC,8250.0,Suzuki,2023,687637.50
2,Suzuki Celerio 2019,Automatic,1000 CC,10499.0,Suzuki,2019,875091.65
3,Changan E Star 2023,Automatic,0 CC,10990.0,Changan,2023,916016.50
4,Hyundai Grand i10 2020,Automatic,1250 CC,11500.0,Hyundai,2020,958525.00
...,...,...,...,...,...,...,...
361,Land Rover Range Rover 2023,Automatic / HSE,3000 CC,203350.0,Land,2023,16949222.50
362,Maserati Quattroporte 2022,Automatic / GTS GranLusso,3800 CC\nTurbo,210000.0,Maserati,2022,17503500.00
363,Maserati Levante 2022,Automatic / Trofeo,3800 CC\nTurbo,220000.0,Maserati,2022,18337000.00
364,Genesis GV80 2022,Automatic / Prestige,2500 CC\nTurbo,239500.0,Genesis,2022,19962325.00
365,Cadillac Ecalade V 2023,manual,6200 CC,250000.0,Cadillac,2023,20837500.00

8.   Отсортируйте автомобили по стоимости, начиная с дешевых.

In [69]:
df_sorted = df.sort_values('Цена, руб.', ascending=True)
df_sorted

,Модель,КПП,Мощность,"Цена, дол.",Марка,Год,"Цена, руб."
0,Byd F0 2018,Manual,1000 CC,6900.0,Byd,2018,575115.00
1,Suzuki Alto 2023,manual,800 CC,8250.0,Suzuki,2023,687637.50
2,Suzuki Celerio 2019,Automatic,1000 CC,10499.0,Suzuki,2019,875091.65
3,Changan E Star 2023,Automatic,0 CC,10990.0,Changan,2023,916016.50
4,Hyundai Grand i10 2020,Automatic,1250 CC,11500.0,Hyundai,2020,958525.00
...,...,...,...,...,...,...,...
361,Land Rover Range Rover 2023,Automatic / HSE,3000 CC,203350.0,Land,2023,16949222.50
362,Maserati Quattroporte 2022,Automatic / GTS GranLusso,3800 CC\nTurbo,210000.0,Maserati,2022,17503500.00
363,Maserati Levante 2022,Automatic / Trofeo,3800 CC\nTurbo,220000.0,Maserati,2022,18337000.00
364,Genesis GV80 2022,Automatic / Prestige,2500 CC\nTurbo,239500.0,Genesis,2022,19962325.00
365,Cadillac Ecalade V 2023,manual,6200 CC,250000.0,Cadillac,2023,20837500.00

9.   Найдите самую дорогую машину.

In [71]:
df_sorted.iloc[-1]

Модель        Cadillac Ecalade V 2023
КПП                            manual
Мощность                      6200 CC
Цена, дол.                   250000.0
Марка                        Cadillac
Год                              2023
Цена, руб.                 20837500.0
Name: 365, dtype: object

10.  Отсортируйте автомобили по критерию "Самая дешевая лошадинная сила".

In [74]:
df['Мощность'] = df['Мощность'].str.extract(r'(\d+)').astype(int)
df['Цена за силу'] = df['Цена, дол.'] / df['Мощность']
df_sorted = df.sort_values('Цена за силу', ascending=True)

AttributeError: Can only use .str accessor with string values!

In [76]:
df_sorted

,Модель,КПП,Мощность,"Цена, дол.",Марка,Год,"Цена, руб.",Цена за силу
0,Byd F0 2018,Manual,1000,6900.0,Byd,2018,575115.0,6.900000
5,Baic X35 2023,manual / MT,1500,11900.0,Baic,2023,991865.0,7.933333
6,Nissan Micra 2020,Automatic,1500,11950.0,Nissan,2020,996032.5,7.966667
16,Lada Vesta 2019,Automatic,1600,14500.0,Lada,2019,1208575.0,9.062500
4,Hyundai Grand i10 2020,Automatic,1250,11500.0,Hyundai,2020,958525.0,9.200000
...,...,...,...,...,...,...,...,...
83,GAC Aion 2023,Automatic / Y,0,23750.0,GAC,2023,1979562.5,inf
82,Nissan LEAF 2020,Automatic / 40kWh,0,23500.0,Nissan,2020,1958725.0,inf
294,Tesla Model S 2020,Automatic,0,76990.0,Tesla,2020,6417116.5,inf
75,Baic EU5 Plus 2024,Automatic / Electric,0,22900.0,Baic,2024,1908715.0,inf
341,Porsche Taycan Cross Turismo 2023,Automatic / Turbo,0,116000.0,Porsche,2023,9668600.0,inf