In [1]:
import pandas as pd

1. Создать Dataframe на базе csv

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2.   Проверить, существуют ли пропущенные значение в данных.

In [32]:
any(df.isnull())

True

3.   Получить наименование столбцов с пропущенными значениями и их количество

In [14]:
counter = df.isnull().sum()
cols = counter[counter > 0]
cols

Age         177
Cabin       687
Embarked      2
dtype: int64

4.   Заменить пропущенные значение в столбце Age в зависимости от столбца Name. Самостоятельно предложить решение.

In [15]:
df['Title'] = df['Name'].str.extract(r',\s*([^\.]*)\.', expand=False)
median = df.groupby('Title')['Age'].median()
median

Title
Capt            70.0
Col             58.0
Don             40.0
Dr              46.5
Jonkheer        38.0
Lady            48.0
Major           48.5
Master           3.5
Miss            21.0
Mlle            24.0
Mme             24.0
Mr              30.0
Mrs             35.0
Ms              28.0
Rev             46.5
Sir             49.0
the Countess    33.0
Name: Age, dtype: float64

In [17]:
df['Age'] = df.apply(lambda x: median[x['Title']] if pd.isnull(x['Age']) else x['Age'], axis=1)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

5.   Проверить, присутствуют ли дубликаты в данных по всем столбцам.

In [20]:
df.duplicated().sum()

0

6.   Проверить присутствие дубликатов по разным подмножествам столбцов.

In [21]:
duplicates_name_age = df.duplicated(subset=['Name', 'Age']).sum()
print(f"Дубликаты по Name и Age: {duplicates_name_age}")

duplicates_ticket_pclass = df.duplicated(subset=['Ticket', 'Pclass']).sum()
print(f"Дубликаты по Ticket и Pclass: {duplicates_ticket_pclass}")

duplicates_cabin_sex = df.duplicated(subset=['Cabin', 'Sex']).sum()
print(f"Дубликаты по Cabin и Sex: {duplicates_cabin_sex}")

Дубликаты по Name и Age: 0
Дубликаты по Ticket и Pclass: 210
Дубликаты по Cabin и Sex: 718

7.   Заменить значение female на 0, а male на 1 в столбце Sex.

In [22]:
df['Sex'] = df['Sex'].map({'female': 0, 'male': 1})
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S,Mr

8.   Выделить в новый признак титулы из имени и посчитать сколько количество Mr и Miss.

In [26]:
ct = df['Title'].value_counts()
print(f'Mr: {ct['Mr']}')
print(f'Miss: {ct['Miss']}')

Mr: 517
Miss: 182

9.   Cоздать новый признак FamilySize (размер семьи) как комбинацию SibSp и Parch

In [27]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,2
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S,Mrs,2
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S,Mr,1

10.  Создаем новый признак IsAlone - один или с семьей.

In [28]:
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,FamilySize,IsAlone
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,2,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,2,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S,Mrs,2,0
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S,Mr,1,1